### PR TITLE
Make RQ proc counting more efficient / correct

### PR DESCRIPTION
**Pull request by jon-torodash**
As requested, for #48: a change set to exclusively focus on RQ's counting.

### CODE REVIEW

**Comment by jon-torodash** [comment]
For the sake of issue referentiality: #12

**Comment by codingjoe** [comment]
I haven't used rq before, @ryanhiebert do you have more experience here?

Thanks @jon-torodash for cleaning up the PR, much appreciated.

**Comment by jon-torodash** [comment]
I will address whatever bugs I can within my capacity. In my project, I've overridden the middleware to catch the quantity method with similar code, and I'd be all too happy to have a performing library I don't need to patch rather than have to revert back myself. If it's any further assurance, test coverage of the rq implementation in HireFire seemed very low. I invite you to try consider the test's validity and run it against the prior implementation: it will fail.

**Comment by ryanhiebert** [comment]
That sounds like the commitment I was wanting to get from you, thank you @jon-torodash .

**Comment by jon-torodash** [comment]
Do I need to do anything further to get it merged in?

**Comment by ryanhiebert** [comment]
Nope. I gave you a green review, and I sent you an invitation to be a collaborator. Accept the invitation, and hit the merge button!

**Comment by jon-torodash** [comment]
I'm sorry, are you sure that got sent? I don't see the invitation anywhere.

**Comment by ryanhiebert** [comment]
Yep. Click this link and see what you see: https://github.com/ryanhiebert/hirefire/invitations

**Pull request merged**
